[default_session]
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "sesh config"
path = "~/dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "neovim config"
path = "~/dotfiles/.config/nvim"
startup_command = "nvim init.lua"

[[session]]
name = "tmux config"
path = "~/dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "alacritty config"
path = "~/dotfiles/.config/alacritty"
startup_command = "nvim alacritty.toml"

[[session]]
name = "zsh config"
path = "~/dotfiles"
startup_command = "nvim .zshrc"
