[default_session]
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "neovim config"
path = "~/.config/nvim"
startup_command = "nvim init.lua"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "alacritty config"
path = "~/.config/alacritty"
startup_command = "nvim alacritty.toml"
