import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
blur = true
decorations = "Buttonless"
padding = { x = 15, y = 15 }

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002T"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = 18
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = 19
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = 20
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = 21
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = 23
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = 22
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = 26
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = 28
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = 25
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:qa!
"""
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "|"
key = "Semicolon"
mods = "Alt"

[[keyboard.bindings]]
chars = "{"
key = 23
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 23
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "}"
key = 27
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 27
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "~"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = 47
mods = "Alt|Shift"
